### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by GodloveD** [Yyx2626/HTGTSrep#1]
Hi there!  I'm an admin who's been asked to install this for a user.  I'd like to test the installation and make sure it's working.  Are you able to supply some small sample data, and commands or a test script to verify the installation?  That would be supremely helpful.  Thanks!

**Comment by GodloveD** [comment]
Sorry.  I missed that there was a `test` subdirectory on the bitbucket repo.  But even so, I still don't know how to test this.  I'm getting the following:

```
$ python HTGTSrep.py run \
    -m /path/to/data/metadata.txt \
    -o /path/to/data/out

Welcome to HTGTSrep pipeline!!!
INFO  @ Thu, 05 Mar 2020 17:39:39: Parameters: HTGTSrep.py run -m /path/to/data/metadata.txt -o /path/to/data/out
ERROR @ Thu, 05 Mar 2020 17:39:39: No sequence file is specified
```
I don't see any options that mention a sequence file.  Is this supposed to be specified in metadata.txt?

**Comment by Yyx2626** [comment]
I am sorry that we have not prepared a test dataset yet; perhaps we should prepare one soon. 

For the options, You can see the command-line help page by '-h' option.  For example, 'python HTGTSrep.py run -h' will show that you can use '-r1 R1.fq' and '-r2 R2.fq' to specify the sequence files.

**Comment by Yyx2626** [comment]
Hi GodloveD,

I have just uploaded the demo test dataset with the expected output, and updated README.md for HTGTSrep.  I hope this demo test dataset helps.
